# Site settings
title: WIZZYSHOP API
email: geral@codigoirreverente.com
description: > # this means to ignore newlines until "baseurl:"
  Wizzyshop's API by <a href='http://www.codigoirreverente.com' target='_new()'>Código Irreverente.</a>
baseurl: "/wizzyapi/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
